RESUMEN_PRODUCCION = "Information/resumen_produccion.xlsx"

MATERIA_PRIMA_TORTAS = ["AZUCAR GRANULADO", "HUEVOS FRESCOS", "HARINA DE TRIGO","GRASA VEGETAL ELITE", "GRASA VEGETAL VIVI", "COCOA NATURAL", "AREQUIPE",
    "FECULA", "ESENCIA DE NARANJA", "POLVO DE HORNEAR", "ESENCIA DE BANANO", "BREVAS", "UVAS PASAS", "CIRUELAS", "COLOR CARAMELO", "ESENCIA DE CANELA", 
    "ESENCIA VAINILLA CARAMELO","ESENCIA DE MANTEQUILLA","PONY MALTA","CREMA DE TIRAMISU","MIXO","ESENCIA VAINILLA PASION","CAFE INSTANTANEO",
    "SEMILLAS DE AMAPOLA","MANZANA","MANI","CONSERVANTE"]